# Generated by Django 3.0.3 on 2021-08-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0002_auto_20210806_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
